language: java
before_script:
- unset _JAVA_OPTIONS
- cd finish
script:
- mvn clean install
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: fSemVEgZdTk8dXlc6jF0X4kKcOYHf3NLNo6GIhLrYRtBhEGMd9a6y4UEfYs5m9juVehvVQFmnn5qHkQYUbTYbhjZBb1ZoXPX1mwRXVOTm1tCO6dPnSIKRXpiPZeenb1+g1pf4tkF1L0xlyq/nnMLa33gDNC0u9YJXdVFnIHgzfjB7ocpLPh7Gg+GG0nldVJ7X4vQfQVIFumDCjLyJPdqb+Tqz3Clc4zgkZFDZd6uIJZp5WBp/B7FIXryY3PGZMsW4TBXS1i8iPUWIPke2Bu79HwJ1ur6iBf8YdhCabB7fOo4MneXV00Dva6WRqHP/G4AIsf22CbLD6WyQtFqUUwXdVvUvK8cJ4iOBqh5OE2NrB+L1lfwa/G0tFpzZ/bEKZQ47t6RJDrrMGq6S7PmYMUsu7jloY26PMY/oaAKcJY0wk1T0JBh+IdWhlXC8nLMk5PMHKY5+9pLG3OB/NqjG0QPXBYF6kjp99/ix4/rpWkGK2YOMgJftgfAHaRLVJobNvFxlOGCNmmU3YhCYoOFHZsQevgHboD++BNNEAq6oPiOedhMA3S6PlBXLVwgi8y01ndG4eKbf8e6hc/E3dpZM5poT0TYF0I/VFQX5LuaIAWw96AePIn1nbpwvd1OTX/wpUPFJtA8X4pt8JRsCxeZzyjhNbACyFF9vjDxhbmUxCSbJg8=
    on_success: never
    on_failure: always
branches:
  only:
  - master
