language: java
before_script:
- unset _JAVA_OPTIONS
- cd finish
script:
- mvn clean install
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: UhunfuuclcLuBw/qBEu0d1iHeAw4GxBBspkiUyqX9Sz1+96qLRPjp34Wpm2xxsuCKsewXQcmU4hbVyRczFgfJIVpvQwJD99yGdlZIsI3SCrCkA5SF+M+ihcVgBUi4brT+mEQeO5ZB05mtGFjeZodJ2wwgQGvgRabOrBZYKo6em7LslfLUYISbVSCEsau3Es0AinXJhPdXJnL1DPZR+u1nxsG4gS3JGSZMllNZU43pbWjmyJeeb/NEBDTrCQJHgBJYJ1+C+q2jqtoP6P+gNnPGNQRlqHiSTDLAKhcC1RDzToJ4O8+8k5YXjonn3wgIFjpETMEjXjakg/1l4+fttXFFMDMtjGl1/SH44ZwRFue1V/2or1Rn2v61cmH06MpnfJeiT326/OfnHUL+lwbdyf8pYZOoGaAZCzvz0nA5JscSHxoDGOugAvhYZdXbsx9/cpauBG97/eOzHfahxJ+42u79NarcNG9AoprGlreCv4nzVmIEIPscq9lIu9qIAH2XPkTG74FRdpnnft9WfBpe/5Qhl1+9xlexXV8Os62EJ0yd6Gx8mfXqbuIHX2K/Zn+yVPfMD01GYA31M8UJ/Bsrs7bpFEyc5nbfXAcq3wVrh/nglUSHSgff3H6ZyUgUDAstfSKblQ7T/HSRrN6m+NDC9SNvLIiYt8P3GhV3sfPzcpdtCE=
    on_success: never
    on_failure: always
branches:
  only:
  - master
